# Demo 3: Demo 3: NumPy basics and vectorized computation 

In [1]:
import numpy as np

### Q1. Generate a 3x4 NumPy array with random integers between 1 and 50. 

In [2]:
arr = np.random.randint(1, 50, size=(3,4))
print(arr)

[[48 11 48 48]
 [ 1 34 47  7]
 [40 45 47 29]]


> A. Calculate and print the Mean, Median, and Standard Deviation 
of the array 

In [3]:
print("Mean is : ", np.mean(arr))
print("Median is: ", np.median(arr))
print("Standard deviation is: ", np.std(arr))

Mean is :  33.75
Median is:  42.5
Standard deviation is:  16.966265548631103


> B. Print the Sum of all elements and the sum of each row. 

In [4]:
print("Sum of elements is: ", np.sum(arr))
print("Sum of row 1: ", np.sum(arr[0]))
print("Sum of row 1: ", np.sum(arr[1]))
print("Sum of row 1: ", np.sum(arr[2]))

Sum of elements is:  405
Sum of row 1:  155
Sum of row 1:  89
Sum of row 1:  161


> C. Reshape the 3x4 array into a 2x6 array and print it. 

In [5]:
arr.reshape(2, 6)
print(arr)

[[48 11 48 48]
 [ 1 34 47  7]
 [40 45 47 29]]


### Q2. Create two (3 * 3) matrices using NumPy and print it. Perform and print the results of the following linear algebra operations 

In [6]:
arr1 = np.random.randint(100, size=(3,3))
arr2 = np.random.randint(100, size=(3,3))
print("Matrix 1: \n", arr1)
print("Matrix 2: \n", arr2)

Matrix 1: 
 [[44  8 28]
 [38 33 71]
 [20 68 27]]
Matrix 2: 
 [[34 89 11]
 [57 20 38]
 [36 59 88]]


> A. Matrix addition 

In [7]:
print("Addition of matrix 1 and matrix 2 is: \n", arr1+arr2)

Addition of matrix 1 and matrix 2 is: 
 [[ 78  97  39]
 [ 95  53 109]
 [ 56 127 115]]


> B. Matrix subtraction 

In [8]:
print("Subtraction of matrix 1 and matrix 2 is: \n", arr1-arr2)

Subtraction of matrix 1 and matrix 2 is: 
 [[ 10 -81  17]
 [-19  13  33]
 [-16   9 -61]]


> C. Matrix multiplication (element-wise and dot product) 

In [9]:
print("Multiplication of matrix 1 and matrix 2 is: \n", arr1*arr2)

Multiplication of matrix 1 and matrix 2 is: 
 [[1496  712  308]
 [2166  660 2698]
 [ 720 4012 2376]]


> D. Transpose of a matrix 

In [10]:
print("Transpose of matrix 1 is: \n", np.transpose(arr1))
print("Transpose of matrix 2 is: \n", np.transpose(arr2))

Transpose of matrix 1 is: 
 [[44 38 20]
 [ 8 33 68]
 [28 71 27]]
Transpose of matrix 2 is: 
 [[34 57 36]
 [89 20 59]
 [11 38 88]]


> E. Determinant and inverse (if applicable) 

In [11]:
det1 = np.linalg.det(arr2)
det2 = np.linalg.det(arr1)
print("Determinant of matrix 1 is: \n", det1)
print("Determinant of matrix 2 is: \n", det2)
if det1!=0 and det2!=0:
    print("Inverse of matrix 1 is: \n", np.linalg.inv(arr1))
    print("Inverse of matrix 2 is: \n", np.linalg.inv(arr2))

Determinant of matrix 1 is: 
 -311987.00000000006
Determinant of matrix 2 is: 
 -116203.99999999978
Inverse of matrix 1 is: 
 [[ 0.03388007 -0.01452618  0.00306358]
 [-0.00339059 -0.00540429  0.01772744]
 [-0.01655709  0.02437093 -0.00987918]]
Inverse of matrix 2 is: 
 [[ 0.00154494  0.0230234  -0.01013504]
 [ 0.01169279 -0.00832086  0.0021315 ]
 [-0.00847151 -0.0038399   0.01408071]]


### Additional Question

Case Study 3: Image processing - Grayscale image
A grayscale image is scored as 2D numpy array of size (256x256) with pixel intensity values ranging from 0 to 255 
1. Normalise the pixel values between zero and one
2. increase the brightness by 20 units ensuring that value doesn't increase 255
3. Extract the central 100x100 region of the image
4. Count the number of pixels with intensity `

In [35]:
arr = np.random.randint(256, size=(256, 256))
print(arr)

[[ 42  94 122 ...  49  85 168]
 [253 160 176 ... 105  30   3]
 [228 185 185 ... 121 214  33]
 ...
 [ 23   6 153 ... 248 252 223]
 [ 23  99 139 ...   5 235 126]
 [ 12 195  29 ... 113  26  61]]


In [36]:
arr = arr * (1/255)
print(arr)

[[ 42  94 122 ...  49  85 168]
 [253 160 176 ... 105  30   3]
 [228 185 185 ... 121 214  33]
 ...
 [ 23   6 153 ... 248 252 223]
 [ 23  99 139 ...   5 235 126]
 [ 12 195  29 ... 113  26  61]]
[[0.16470588 0.36862745 0.47843137 ... 0.19215686 0.33333333 0.65882353]
 [0.99215686 0.62745098 0.69019608 ... 0.41176471 0.11764706 0.01176471]
 [0.89411765 0.7254902  0.7254902  ... 0.4745098  0.83921569 0.12941176]
 ...
 [0.09019608 0.02352941 0.6        ... 0.97254902 0.98823529 0.8745098 ]
 [0.09019608 0.38823529 0.54509804 ... 0.01960784 0.92156863 0.49411765]
 [0.04705882 0.76470588 0.11372549 ... 0.44313725 0.10196078 0.23921569]]


In [37]:
arr = arr + 20
print(arr)

[[20.16470588 20.36862745 20.47843137 ... 20.19215686 20.33333333
  20.65882353]
 [20.99215686 20.62745098 20.69019608 ... 20.41176471 20.11764706
  20.01176471]
 [20.89411765 20.7254902  20.7254902  ... 20.4745098  20.83921569
  20.12941176]
 ...
 [20.09019608 20.02352941 20.6        ... 20.97254902 20.98823529
  20.8745098 ]
 [20.09019608 20.38823529 20.54509804 ... 20.01960784 20.92156863
  20.49411765]
 [20.04705882 20.76470588 20.11372549 ... 20.44313725 20.10196078
  20.23921569]]
