# PANDAS

# NUMPY

In [23]:
import numpy as np

---
### <center>Creating an Array</center>

<br></br>

> Manual 2D array

In [36]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

<br> </br>

> Constant Filled Array

In [ ]:
B = np.zeros((3, 4))
# array([[0., 0., 0., 0.],
#        [0., 0., 0., 0.],
#        [0., 0., 0., 0.]])

B = np.zeros_like(A)    # Zeros with same shape as A
# array([[0., 0., 0., 0.],
#        [0., 0., 0., 0.],
#        [0., 0., 0., 0.]])

B = np.ones((3,4))      #Array filled with 1
# array([[1., 1., 1., 1.],
#        [1., 1., 1., 1.],
#        [1., 1., 1., 1.]])

B = np.full((3, 4), 7)  #Array filled with value n
# array([[7, 7, 7, 7],
#        [7, 7, 7, 7],
#        [7, 7, 7, 7]])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<br></br>

> Numeric Ranges Array

In [54]:
C = np.arange(10)       # 0 to 9
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

C = np.linspace(0, 1, 5)       # 5 evenly spaced values from 0 to 1
# array([0.  , 0.25, 0.5 , 0.75, 1.  ])

<br></br>

> Random Arrays

In [ ]:
D = np.random.randn(3, 4)   # Standard normal distribution
# array([[-0.0760774 , -0.03200337, -0.100363  , -0.23874902],
#        [-0.07374158, -0.19705889,  0.43235924, -1.65472284],
#        [ 0.33312586,  0.65547935,  0.01464331,  0.13430627]])

D = np.random.rand(3, 4)   #Random values 0 to 1
# array([[0.52572514, 0.07047212, 0.83178078, 0.55178461],
#        [0.54782116, 0.35726071, 0.4218132 , 0.4696169 ],
#        [0.16579049, 0.3354292 , 0.63955975, 0.67816183]])

D = np.random.choice([1, 2, 3], size=(3,4)) #Random from this list
# array([[2, 1, 1, 2],
#        [2, 3, 3, 3],
#        [3, 1, 3, 1]])

<br></br>

> Structured Creation 

In [ ]:
E = np.concatenate([A, B])      # Combine arrays
# array([[ 56. ,   0. ,   4.4,  68. ],
#        [  1.2, 104. ,  52. ,   8. ],
#        [  1.8, 135. ,  99. ,   0.9],
#        [  7. ,   7. ,   7. ,   7. ],
#        [  7. ,   7. ,   7. ,   7. ],
#        [  7. ,   7. ,   7. ,   7. ]])

E = np.repeat([1, 2, 3], 3)     # Repeat each element
# array([1, 1, 1, 2, 2, 2, 3, 3, 3])

--- 
### <center> Array Arguments </center>

--- 
### <center> Matrix Operations </center>

In [40]:
# Go Vertically X=0
row = A.sum(axis=0)

# Go Horizontally X=1
column = A.sum(axis=1)