In [ ]:
# week 3 programs on numpy
-Riya Agrawal
-class:PF rollno:46
-date:22/01/2026

In [3]:
"""1. Generate a 3x4 NumPy array with random integers between 1 
and 50. 
a. Calculate and print the Mean, Median, and Standard Deviation 
of the array 
b. Print the Sum of all elements and the sum of each row. 
c. Reshape the 3x4 array into a 2x6 array and print it."""

import numpy as np
arr=np.random.randint(1,51,size=(3,4))
print("array:",arr)
print("array:\n",arr)
print("\nmean:",np.mean(arr))
print("Median:",np.median(arr))
print("Std:",np.std(arr))
print("\nsum of all elements:",np.sum(arr))
print("row wise sum:",np.sum(arr,axis=1))
print("reshaped to 2x6:\n",arr.reshape(2,6))

array: [[22 50 50  1]
 [17 38  8 22]
 [ 2  9 37 14]]
array:
 [[22 50 50  1]
 [17 38  8 22]
 [ 2  9 37 14]]

mean: 22.5
Median: 19.5
Std: 16.68582232515577

sum of all elements: 270
row wise sum: [123  85  62]
reshaped to 2x6:
 [[22 50 50  1 17 38]
 [ 8 22  2  9 37 14]]


In [5]:
"""2. Create two (3 * 3) matrices using NumPy and print it. Perform 
and print the results of the following linear algebra operations 
a. Matrix addition 
b. Matrix subtraction 
c. Matrix multiplication (element-wise and dot product) 
d. Transpose of a matrix 
e. Determinant and inverse (if applicable)"""

import numpy as np
x1=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

x2=np.array([[10,11,12],
            [13,14,15],
            [16,17,28]])
print("add 2 matrices:",x1+x2)
print("subtract 2 matrices:",x2-x1)
print("multiplication elementwise:",x1*x2)
print("dot product:",x1@x2)
print("Transpose of matrix x1:",x1.T)
print("Transpose of matrix x2:",x2.T)
det_x1=np.linalg.det(x1)
print("determinant of x1:",det_x1)
inv_x1=np.linalg.inv(x1)
print("\ninverse of x1:\n",inv_x1)
det_x2=np.linalg.det(x2)
print("determinant of x2:",det_x2)
inv_x2=np.linalg.inv(x2)
print("inverse of x2:",inv_x2)

add 2 matrices: [[11 13 15]
 [17 19 21]
 [23 25 37]]
subtract 2 matrices: [[ 9  9  9]
 [ 9  9  9]
 [ 9  9 19]]
multiplication elementwise: [[ 10  22  36]
 [ 52  70  90]
 [112 136 252]]
dot product: [[ 84  90 126]
 [201 216 291]
 [318 342 456]]
Transpose of matrix x1: [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of matrix x2: [[10 13 16]
 [11 14 17]
 [12 15 28]]
determinant of x1: -9.51619735392994e-16
inverse of x1: [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
determinant of x2: -29.99999999999999
inverse of x2: [[-4.56666667  3.46666667  0.1       ]
 [ 4.13333333 -2.93333333 -0.2       ]
 [ 0.1        -0.2         0.1       ]]
