# data visualization week 3 
- Name:Riya Agrawal
- reg no.:251090052030
- class:PF rollno.:(46)
- date:22/01/2026
- topic:Numerical python

In [1]:
import numpy as np
np.__version__

'1.21.5'

In [2]:
lst=[1,2,3,4]
arr=np.array(lst)
print("list:",lst)
print("Array:",arr)


list: [1, 2, 3, 4]
Array: [1 2 3 4]


In [3]:
print(type(lst))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
print("array+5",arr+5)
print("Array*2",arr*2)
print("array square:",arr**2)

array+5 [6 7 8 9]
Array*2 [2 4 6 8]
array square: [ 1  4  9 16]


In [5]:
arr

array([1, 2, 3, 4])

In [6]:
arr-3

array([-2, -1,  0,  1])

In [7]:
arr/10

array([0.1, 0.2, 0.3, 0.4])

In [10]:
np.zeros((2,3)) #2x3 matrix of zeros
np.ones((3,2))  #3x2 matrix of ones
np.arange(1,10) #1D array of n-1 values where n=10
np.random.randint(1,20,size=(3,4)) # random values of 3x4 matrix 


array([[13, 11,  2,  6],
       [11, 17, 15, 11],
       [10, 10, 13,  2]])

In [11]:
print("matrix of zeros:",np.zeros((2,3)))
print("matrix of ones:",np.ones((3,2)))
print("Matrix of 1...9:",np.arange(1,10))

matrix of zeros: [[0. 0. 0.]
 [0. 0. 0.]]
matrix of ones: [[1. 1.]
 [1. 1.]
 [1. 1.]]
Matrix of 1...9: [1 2 3 4 5 6 7 8 9]


In [13]:
#create a random 4x56 integer array between 10 and 99 and print it
arr=np.random.randint(10,99,size=(4,5))
print(arr)

[[23 19 88 45 84]
 [30 50 24 48 75]
 [18 84 54 87 25]
 [11 17 97 54 53]]


In [18]:
A=np.random.randint(1,51,size=(3,4))
print("A:\n",A)
print("\nshape:",A.shape)
print("ndim:",A.ndim)
print("Size:",A.size)
print("Dtype:",A.dtype)

A:
 [[ 2 18 36 12]
 [10 14 15 16]
 [ 8 33 33 25]]

shape: (3, 4)
ndim: 2
Size: 12
Dtype: int32


In [24]:
B=np.array([[11,12,13,14],
            [21,22,23,24],
            [31,32,33,34]])
print("B:\n",B)
print("\nelement at row 1,column 2 [1,2]:",B[1,2])
print("First row:",B[0])
#or
print("third row:",B[2,:])
print("second column:",B[:,1])

B:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

element at row 1,column 2 [1,2]: 23
First row: [11 12 13 14]
third row: [31 32 33 34]
second column: [12 22 32]


In [ ]:
#print the third column
print("Third column:",B[3,:])
print("First 2 rows:",B[])
#print the 2x2 matrix at the top left corner of B
print("2x2 matrix:",B[0

In [28]:
arr3D=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [29]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
type(arr3D)

numpy.ndarray

In [31]:
oldv=arr3D[0].copy()
arr3D[0]=42
print(arr3D)
print("-------------")
arr3D[0]=oldv
print(arr3D)

[[[42 42 42]
  [42 42 42]
  [42 42 42]
  [42 42 42]]]
-------------
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [32]:
x=np.array([[2,8,1],
           [5,3,9]])
print("x:\n",x)
print("\nmean:",np.mean(x))
print("Median:",np.median(x))
print("Std:",np.std(x))

x:
 [[2 8 1]
 [5 3 9]]

mean: 4.666666666666667
Median: 4.0
Std: 2.981423969999719


In [34]:
#create a random 3x4 matrix and compute mean,median and standard deviation
arr=np.random.randint(1,10,size=(3,4))
print("array:\n",arr)
print("\nmean:",np.mean(arr))
print("Median:",np.median(arr))
print("Std:",np.std(arr))

array:
 [[5 5 4 7]
 [6 6 7 3]
 [5 2 6 4]]

mean: 5.0
Median: 5.0
Std: 1.4719601443879744


In [48]:
#axis=0 means down the rows
#axis=1 means across the column
print("x:\n",x)
print("\nsum of all elements:",np.sum(x))
print("row wise sum:",np.sum(x,axis=1))
print("column wise sum:",np.sum(x,axis=0))

x:
 [[2 8 1]
 [5 3 9]]

sum of all elements: 28
row wise sum: [11 17]
column wise sum: [ 7 11 10]


In [37]:
flat=np.arange(1,13)
M=flat.reshape(3,4)
print("flat:",flat)
print("\nreshaped to 3x4:\n",M)
print("reshaped to 2x6:\n",M.reshape(2,6))

flat: [ 1  2  3  4  5  6  7  8  9 10 11 12]

reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshaped to 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [44]:
z=np.array([[1,2,3],
            [4,5,6]])
add_row=np.array([10,20,30])
add_col=np.array([[100],[200]])
print("Z:\n",z)
print("\nZ + add row:\n",z+add_row)
print("\nZ + add column:\n",z+add_col)


Z:
 [[1 2 3]
 [4 5 6]]

Z + add row:
 [[11 22 33]
 [14 25 36]]

Z + add column:
 [[101 102 103]
 [204 205 206]]


In [45]:
M1=np.array([[1,2,3],
            [8,1,4],
            [5,6,9]])

M2=np.array([[5,3,7],
            [2,9,2],
            [6,1,8]])
print("add M1 and M2:",M1+M2)
print("subtract M1 and M2:",M1-M2)

add M1 and M2: [[ 6  5 10]
 [10 10  6]
 [11  7 17]]
subtract M1 and M2: [[-4 -1 -4]
 [ 6 -8  2]
 [-1  5  1]]


In [47]:
import numpy as np
A=([[1,1],
     [1,2]])
det_A=np.linalg.det(A)
print("determinant of A:",det_A)
inv_A=np.linalg.inv(A)
print("inverse of A:",inv_A)

determinant of A: 1.0
inverse of A: [[ 2. -1.]
 [-1.  1.]]
