In [1]:
# Name: Chhayank Sharma
# Registration no.: 60
# Demo given to introduce numpy basics for DAV lab

In [2]:
import numpy as np
np.__version__

'1.21.5'

In [14]:
myarr = np.arange(1000000)
mylis = list(range(1000000))

In [15]:
%timeit myarr2 = myarr * 2
%timeit mylis2 = [x * 2 for x in mylis]

1.18 ms ± 11.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
62.6 ms ± 462 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [16]:
data = np.array([[1,2.3,3],[4.3,5,6.7]])
data*10

array([[10., 23., 30.],
       [43., 50., 67.]])

In [17]:
data+data

array([[ 2. ,  4.6,  6. ],
       [ 8.6, 10. , 13.4]])

In [19]:
data.shape

(2, 3)

In [20]:
data = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[1,2,3]]])

In [21]:
data

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [1, 2, 3]]])

In [24]:
data.ndim

3

In [25]:
data.dtype

dtype('int32')

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [48]:
data = np.random.rand(2,3)*100
data

array([[ 0.98317995, 78.52196837, 64.80324652],
       [86.9936508 , 47.71106091, 23.50369823]])

In [49]:
data.astype(np.int32)

array([[ 0, 78, 64],
       [86, 47, 23]])

In [50]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [51]:
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [52]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [53]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [56]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [57]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])