In [1]:
# Name: Chhayank Sharma
# Registration no.: 60
# Generate a 3x4 NumPy array with random integers between 1 and 50. 
#     a. Calculate and print the Mean, Median, and Standard Deviation of the array 
#     b. Print the Sum of all elements and the sum of each row. 
#     c. Reshape the 3x4 array into a 2x6 array and print it.

In [3]:
import numpy as np

In [7]:
data = np.random.randint(1,51,size=(4,3))
print(data)

[[36  2 25]
 [26 48  5]
 [ 9 39 15]
 [48 50 49]]


In [15]:
print(f"mean: {data.mean()}")
print(f"median: {np.median(data)}")
print(f"standard deviation: {np.std(data)}")

mean: 29.333333333333332
median: 31.0
standard deviation: 17.40849090402599


In [19]:
print(f"sum of all elements: {data.sum()}")
for i in range(data.shape[0]):
    print(f"sum or row {i+1}: {data[i].sum()}")

sum of all elements: 352
sum or row 1: 63
sum or row 2: 79
sum or row 3: 63
sum or row 4: 147


In [22]:
print(f"reshaped matrix:\n{np.reshape(data, (6, 2))}")

reshaped matrix:
[[36  2]
 [25 26]
 [48  5]
 [ 9 39]
 [15 48]
 [50 49]]
