In [28]:
# Name: Chhayank Sharma
# Registration no.: 60
# Create two (3 * 3) matrices using NumPy and print it.
# Perform and print the results of the following linear algebra operations 
# a. Matrix addition 
# b. Matrix subtraction 
# c. Matrix multiplication (element-wise and dot product) 
# d. Transpose of a matrix 
# e. Determinant and inverse (if applicable) 

In [4]:
import numpy as np

In [16]:
arr1 = np.random.randint(1,51,size=(3,3))
print(f"A:\n{arr1}")
arr2 = np.random.randint(1,51,size=(3,3))
print(f"\nB:\n{arr2}")

A:
[[45 21 41]
 [30  2 32]
 [45 16 21]]

B:
[[16 37 20]
 [ 9 40 18]
 [38  7 28]]


In [17]:
print(f"A+B:\n{arr1+arr2}")

A+B:
[[61 58 61]
 [39 42 50]
 [83 23 49]]


In [18]:
print(f"A-B:\n{arr1-arr2}")

A-B:
[[ 29 -16  21]
 [ 21 -38  14]
 [  7   9  -7]]


In [19]:
print(f"Element-wise Multiplication:\n{arr1*arr2}")

Element-wise Multiplication:
[[ 720  777  820]
 [ 270   80  576]
 [1710  112  588]]


In [20]:
print(f"Dot Product:\n{np.dot(arr1,arr2)}")

Dot Product:
[[2467 2792 2426]
 [1714 1414 1532]
 [1662 2452 1776]]


In [21]:
print(f"Transpose(A):\n{np.transpose(arr1)}")
print(f"Transpose(B):\n{np.transpose(arr2)}")

Transpose(A):
[[45 30 45]
 [21  2 16]
 [41 32 21]]
Transpose(B):
[[16  9 38]
 [37 40  7]
 [20 18 28]]


In [22]:
det1 = round(np.linalg.det(arr1),10)
det2 = round(np.linalg.det(arr2),10)
print(f"Determinant(A): {det1}")
print(f"Determinant(B): {det2}")

Determinant(A): 11850.0
Determinant(B): 2748.0


In [23]:
if(det1!=0):
    print(f"Inverse(A):\n{np.linalg.inv(arr1)}")
if(det2!=0):
    print(f"Inverse(A):\n{np.linalg.inv(arr2)}")

Inverse(A):
[[-0.03966245  0.01814346  0.04978903]
 [ 0.06835443 -0.07594937 -0.01772152]
 [ 0.03291139  0.01898734 -0.04556962]]
Inverse(A):
[[ 0.36171761 -0.32605531 -0.04876274]
 [ 0.15720524 -0.11353712 -0.03930131]
 [-0.53020378  0.47088792  0.11171761]]
